# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - api-gateway-xx

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6874facfae7d4f4fae23afb0f04d9c40 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d2f2c7caa2c7435d98214e66522c6ab7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6874facfae7d4f4fae23afb0f04d9c40 }}/api-gateway:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'api-gateway-xx'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d0caacd56b504b7781ce41372d2fd5a4 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6874facfae7d4f4fae23afb0f04d9c40 }}/api-gateway:${{ github.sha }}'